### ISSUE TITLE
Disable logging in local environment

### ISSUE THREAD

**Issue by szilardd** [microsoft/applicationinsights-angularplugin-js#118]
Is there a way to disable logging? I still want to initialize the logging but in my local environment but I don't want it to trigger sending to App Insights. 

I tried with:
- setting `instrumentationKey` to empty string, but the POST request to App Insigths is always rejected with HTTP status 400 with error message `Invalid instrumentation key`.
- setting `instrumentationKey` to _undefined_, but I get a runtime error `Please provide instrumentation key`

I know that it is possible to set a custom `endpointUrl` as described [here](https://github.com/microsoft/applicationinsights-angularplugin-js/issues/31#issuecomment-974553033) but if I set a dummy URL it still tries to send the logs there and I get an error in the browser console.

Thanks

**Comment by MSNev** [comment]
Yes, there is a `disableTelemetry` configuration that when set to true will process the entire pipeline, but when it is attempted to be "batched" for sending every event is dropped.

I assume you are looking to do this for local / ci testing?

**Comment by szilardd** [comment]
Thanks, it works! Yes, I want to disable logging in my local environment.
