### ISSUE TITLE
pageView always the same time

### ISSUE THREAD

**Issue by landetus** [microsoft/applicationinsights-angularplugin-js#130]
I'm using latest versions for application insights and angular plugin in an angular SPA website:
![image](https://github.com/microsoft/applicationinsights-angularplugin-js/assets/32477701/bee6b5cb-de8b-483f-999f-fb69c6af4514)

I've created a service and initialized it in the app.component.ts and it's sending the data to the azure application insights. The only thing I'm experiencing is that the time for the pageView in the logs is always the same and it's the one whenever the application it's initialized:

![image](https://github.com/microsoft/applicationinsights-angularplugin-js/assets/32477701/7e5217a7-54d1-4b6c-85ec-29fd3744f6b9)
![image](https://github.com/microsoft/applicationinsights-angularplugin-js/assets/32477701/3e783b2a-c0eb-434a-99f1-48fe579bc34a)

As you can see in the images the timestamps are grouped for the time the app is initialized, and the only way to get a new timestamp is reloading the app.

For PageVisitTime this is not happening, I get the right time for each call:
![image](https://github.com/microsoft/applicationinsights-angularplugin-js/assets/32477701/3f7802d5-3a4a-411e-b9f3-2d641aae8dac)

Is this the intended behaviour or am I doing something wrong? 

Thanks in advace.

**Comment by MSNev** [comment]
No, this is a bug in v3.0.3 of Application Insights https://github.com/microsoft/ApplicationInsights-JS/issues/2180

@siyuniu-ms Once we have published v3.0.4 I think we should prepare an updated release of all of the components bumping them away from using 3.0.3 as the base, especially for this plugin and the react-js one.

**Comment by landetus** [comment]
Many thanks @MSNev I'll follow the updates.
