### ISSUE TITLE
Add support for Angular v13

### ISSUE THREAD

**Issue by timja** [microsoft/applicationinsights-angularplugin-js#28]
https://github.com/microsoft/applicationinsights-angularplugin-js/issues/23 was not solved correctly

The actual published package.json is here:
https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/package.json#L4-L7

and it's pinned to Angular 11

cc @xiao-lix

**Comment by StefanSchoof** [comment]
And since now angular 13 is there (https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296), please add 13 also.

**Comment by rhythmnewt** [comment]
*bump*

**Comment by Swellenator** [comment]
bump also

**Comment by alvipeo** [comment]
Hey, team! Are you working on this?

**Comment by alvipeo** [comment]
At please change the title to "v13" :)

**Comment by KaterynaFedorenko** [comment]
Hi, very need support for Angular v13, could you please add it?
Thanks)

**Comment by rhythmnewt** [comment]
We updated to v13. The plugin still works but you have to use the --force flag when restoring to install the unsupported version.

**Comment by alvipeo** [comment]
yeah, I still see:
```
"@angular/compiler-cli": "~11.0.6",
```
in `package.json`...

**Comment by MSNev** [comment]
v2.8.0 is now published to npm

**Comment by plee10** [comment]
Now it is pinned to 13, 12 is not supported and it will not support 14 when that comes out.  This is a poor solution.

**Comment by plee10** [comment]
I do happen to need it for Angular 12 currently.  But please consider that Angular versions having been coming out every six months and there should be flexibility.  If you are asking me, please make it compatible for >= 12.

**Comment by timja** [comment]
13 is fine for me but as others have said if there's no reason to pin to that version then I would suggest being flexible.
But I wouldn't hold back if there's a reason as long as there's a working version for that angular version.

**Comment by MSNev** [comment]
Hi all, we have talked about this internally and based on our current thoughts this is what we are proposing.
- For Angular v11 -> Keep using the older version of the released plugin, as it will be compatible with v11 and will also work with the updated version of AI
- We plan to keep the master branch moving forward to the updated versions from time to time (either with help from the community or by ourselves (once we backfill some open positions)), this means at some point in the future v13 will be in the same situation as Angular v11 is today.
- For Angular v12, we don't have any plans to create a v12 specific version.

This approach should continue working as we plan to keep all future versions of v2.x.x backward compatible (i.e. so the Angular v11 version should continue working).
