### ISSUE TITLE
Wanting to contribute

### ISSUE THREAD

**Issue by timdeschryver** [microsoft/applicationinsights-angularplugin-js#30]
Hi, I'm currently preparing an upgrade from an Angular project from Angular v11 to Angular v12.
The project has a dependency on this library, but due to the listed [peerDependencies](https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/projects/applicationinsights-angularplugin-js/package.json#L5-L6) we're obligated to use the `--force` flag (duplicate of #28). While this works, it's not ideal and it might cause some problems with developers that are not so familiar with it.

I can create a PR with a fix, but I also noticed a few other things that could be approved, hence this issue.
If it's OK, I can create separate PRs for of the following items if you agree:

- chore: update the dependencies of this lib (this also includes Angular and TypeScript) - reason: running `npm install` of this repo results in unmet karma dependencies
- ci: enable the test task during ci - reason: [it's currently commented](https://github.com/microsoft/applicationinsights-angularplugin-js/blob/main/.github/workflows/angular.yml#L29)
- fix: update the peerDependencies to make it compatible with Angular v11 and v12
- chore: replace TSLint with ESLint - reason: TSLint is deprecated

**Comment by timja** [comment]
@timdeschryver generally better to just send a PR with those things, rather than waiting for someone to reply (assuming it won't take too long to do)

(not a maintainer here)

**Comment by timdeschryver** [comment]
I would like to append that with the release of Angular 13, that we also want to change how this package is compiled.
To be specific, to build a partial package, so that the package doesn't need to be compiled by the `ngcc` in the user's project.
[See docs](https://angular.io/guide/creating-libraries#ensuring-library-version-compatibility).

@timja since most of this is "infra" related, I want to make sure that these changes will be positively received - this ensures that all parties involved don't feel bad 😅

**Comment by xiao-lix** [comment]
@timdeschryver Please feel free to send a PR, thanks for the help!

**Comment by timdeschryver** [comment]
Thanks @xiao-lix you can expect some PRs early in December.

**Comment by timdeschryver** [comment]
This is resolved in #34
