### ISSUE TITLE
How does this differ from @microsoft/applicationinsights-web?

### ISSUE THREAD

**Issue by Andrew-Marks-Trisept** [microsoft/applicationinsights-angularplugin-js#46]
Pardon my ignorance, but how is this different from [@microsoft/applicationinsights-web](https://github.com/microsoft/ApplicationInsights-JS)?

I feel like most people are just going to Google something like "how to use app insights in angular" and end up at [this tutorial](https://devblogs.microsoft.com/premier-developer/angular-how-to-add-application-insights-to-an-angular-spa/) from Microsoft, which works great.

The only reason I eventually stumbled on this repo was because App Insights was preventing my Angular app from ever becoming stable (`ApplicationRef.isStable`) and I saw a post somewhere where someone suggested trying this instead.  It didn't fix it, and I couldn't really see any immediate differences in logging or anything, either.

**Comment by timdeschryver** [comment]
@Andrew-Marks-Trisept how I see it, this library is an Angular wrapper around `applicationinsights-web`.
It does the coupling between AI and Angular for you (e.g. the Router, dependency injection, ...).

**Comment by Andrew-Marks-Trisept** [comment]
It seems like `enableAutoRouteTracking: true` handles the route tracking fine, but ok thank you.

**Comment by Andrew-Marks-Trisept** [comment]
P.S. the solution for app insights preventing Angular from becoming stable is to run its methods outside the Angular zone.  See item 1 here: https://github.com/Microsoft/ApplicationInsights-JS/issues/535#issuecomment-787119788.  I didn't need item 2.
