### ISSUE TITLE
Create a compatibility table for the versions of the AngularPlugin -> ApplicationInsights versions

### ISSUE THREAD

**Issue by MSNev** [microsoft/applicationinsights-angularplugin-js#54]
We need to document which versions are compatible with what.

Add a Compatibility table of releases

Should also add Angular versions.

**Comment by kylebradshaw** [comment]
was this ever addressed? I am looking for versions compatible with @angular/common 11.2.14 from a     @microsoft/applicationinsights-angularplugin-js and @microsoft/applicationinsights-web perspective
