### ISSUE TITLE
Missing Dependency either in package.json or documentation

### ISSUE THREAD

**Issue by MichaelPruefer** [microsoft/applicationinsights-angularplugin-js#62]
When following the steps to install/use this plugin, it is stated that i have to use

`npm install @microsoft/applicationinsights-angularplugin-js`

and later in the 'entry component ' i should add:

```typescript
import { ApplicationInsights } from '@microsoft/applicationinsights-web';
import { AngularPlugin } from '@microsoft/applicationinsights-angularplugin-js';
```

But because `@microsoft/applicationinsights-angularplugin-js` does not have the dependency to `@microsoft/applicationinsights-web` and it is nowhere noted that you should install `@microsoft/applicationinsights-web` additionally the rest of the 'Basic Usage' block is not working due to the missing dependency.

So please either add `@microsoft/applicationinsights-web` as a dependency to `@microsoft/applicationinsights-angularplugin-js` **OR** add the additional line `npm install @microsoft/applicationinsights-web`

**Comment by MSNev** [comment]
Year this is a documentation Gap, as the plugin is designed to work with or without the Analytics Plugin (provided as part of the applicationinsights-web module).

And when it's not present the exception handling "silently" doesn't do anything (because there is no-where/way to send the exception)
