### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by cwilliams7** [microsoft/applicationinsights-angularplugin-js#63]
When installing on an Angular 14 app I receive a dependency resolution error:

![image](https://user-images.githubusercontent.com/86806863/175466544-1b70591a-b4c3-4a44-af59-8eab52b4c609.png)

**Comment by roldengarm** [comment]
Yes, I have the same error, preventing me from upgrading to Angular 14. 

I'm a bit worried about the lack of updates to this library

**Comment by MSNev** [comment]
Reopening for release tracking purposes only
