### ISSUE TITLE
[BUG] Angular app does not appear in AppInsights Application map

### ISSUE THREAD

**Issue by danielbecroft** [microsoft/applicationinsights-angularplugin-js#73]
We have an Angular app that interacts with one (or more) .NET Core APIs. We've added the ApplicationInsights JS library to our Angular application, as well as the .NET Core apps. 

In Azure Application Insights, we can correctly see the page views for the Angular app, and we can see the API calls being made in the .NET Core app (with all that logging).

But, in the Application Map, I can only see the API portion, and the items it interacts with ie `[ API ] ==> [ Storage ]`, when I expected to be able to see `[ App ] ==> [ API ] ==> [ Storage ]`. Ideally, we'd be able to see that "user went to `/history`, which then triggered these three (3) calls, and these 25 interactions with external dependencies. 

We are initializing the `ApplicationInsights` object using:

```typescript
    config: {
      instrumentationKey: environment.appInsights.instrumentationKey,
      distributedTracingMode: DistributedTracingModes.W3C,
      autoTrackPageVisitTime: true,
      enableAutoRouteTracking: true,
      enableAjaxErrorStatusText: true
    }
```

and then `.startTrackPage` and `.stopTrackPage`.

Is there anything else that we need to configure to get the full dependency map working in Azure? Or is the Application Map only for server-side components, and not for anything running in the Angular code?

(Apologies if this isn't the correct project to raise the question).

**Comment by jneuhaus20** [comment]
@danielbecroft Did you ever find a solution for this? I have the same scenario (one angular app project, built and deployed to multiple locations, each location accessed by a different domain name.)
