### ISSUE TITLE
Types incompatibility with `@microsoft/applicationinsights-web`

### ISSUE THREAD

**Issue by dzhavat** [microsoft/applicationinsights-angularplugin-js#76]
I have an Angular project with 

```
// package.json
"@microsoft/applicationinsights-angularplugin-js": "3.0.0",
"@microsoft/applicationinsights-web": "2.8.6",
```

If I update `@microsoft/applicationinsights-web` package to v2.8.7, I get an error 

```
Type 'AngularPlugin' is not assignable to type 'ITelemetryPlugin'.
  Types of property 'setNextPlugin' are incompatible.
...
````

![image](https://user-images.githubusercontent.com/1096332/191510097-019e2584-8b09-4047-bbf2-86182fbf92d9.png)

It seems that's because `@microsoft/applicationinsights-web` depends on `@microsoft/applicationinsights-core-js@2.8.7` released 15 days ago, whereas `@microsoft/applicationinsights-angularplugin-js@3.0.0` depends on `@microsoft/applicationinsights-core-js@^2.8.5`.

So given that both `@microsoft/applicationinsights-angularplugin-js` and `@microsoft/applicationinsights-web` we added to a project before the release of `@microsoft/applicationinsights-web@2.8.7`, `@microsoft/applicationinsights-angularplugin-js` will continue to depend on `@microsoft/applicationinsights-core-js@2.8.6` (last version before 2.8.7), whereas `@microsoft/applicationinsights-web@2.8.7` will get a `@microsoft/applicationinsights-core-js@2.8.7` version, thus resulting in types incompatibility.

### Possible solutions

1. Release a new version of `@microsoft/applicationinsights-angularplugin-js` that depends on `@microsoft/applicationinsights-core-js@2.8.7`. This will make `@microsoft/applicationinsights-angularplugin-js` and `@microsoft/applicationinsights-web` use the same version of `@microsoft/applicationinsights-core-js`
2. A manual `yarn upgrade @microsoft/applicationinsights-angularplugin-js` on my side. This was less obvious but apparently running the command results in Yarn updating the `@microsoft/applicationinsights-angularplugin-js`'s dependencies even though the main package didn't have a new version. Took me some time to figure that out.

For now I used solution 2 but solution 1 should be made possible as well.

**Comment by luisamiranda** [comment]
I'm having a similar problem with React Plugin

**Comment by MSNev** [comment]
@luisamiranda what versions? (of the react plugin and application insights) see the [react compatibility matrix](https://github.com/microsoft/applicationinsights-react-js?tab=readme-ov-file#compatibility-matrix)
