### ISSUE TITLE
Repository URL pointing to stale page in another repo

### ISSUE THREAD

**Issue by dzhavat** [microsoft/applicationinsights-angularplugin-js#98]
The `repository.url` property in `package.json` points to a stale page in another repo. Shouldn't it point to this repo instead?

Also, the `repository` is missing from the published package on NPM. https://www.npmjs.com/package/@microsoft/applicationinsights-angularplugin-js?activeTab=code

It'd be nice to include it. In our project we have a script that generates a file with licenses with links to their repos. The script is looking for `repository.url` in `package.json` for finding the link.

**Comment by MSNev** [comment]
> The repository.url property in package.json points to a stale page in another repo. Shouldn't it point to this repo instead?

Yes it should -- thank you for reporting

> Also, the repository is missing from the published package on NPM.

doh! This will be a simulat issue to above (there are 2 package.json files -- one in the root of the repo and one that gets publishing with the package -- the repo is missing from the later one)
